# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\04_About.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_help(object):
    def setupUi(self, Dialog_help):
        Dialog_help.setObjectName("Dialog_help")
        Dialog_help.resize(758, 354)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_help.sizePolicy().hasHeightForWidth())
        Dialog_help.setSizePolicy(sizePolicy)
        Dialog_help.setMinimumSize(QtCore.QSize(758, 354))
        Dialog_help.setMaximumSize(QtCore.QSize(758, 354))
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_help)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Dialog_help)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_picture = QtWidgets.QLabel(self.frame)
        self.label_picture.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_picture.setText("")
        self.label_picture.setTextFormat(QtCore.Qt.RichText)
        self.label_picture.setPixmap(QtGui.QPixmap(":/pic/kikusui_picture.jpg"))
        self.label_picture.setScaledContents(True)
        self.label_picture.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_picture.setObjectName("label_picture")
        self.verticalLayout_2.addWidget(self.label_picture)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setOpenExternalLinks(True)
        self.label_3.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.label_email = QtWidgets.QLabel(self.frame)
        self.label_email.setOpenExternalLinks(False)
        self.label_email.setTextInteractionFlags(QtCore.Qt.TextBrowserInteraction)
        self.label_email.setObjectName("label_email")
        self.verticalLayout_2.addWidget(self.label_email)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_help)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog_help)
        self.buttonBox.accepted.connect(Dialog_help.accept)
        self.buttonBox.rejected.connect(Dialog_help.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_help)

    def retranslateUi(self, Dialog_help):
        _translate = QtCore.QCoreApplication.translate
        Dialog_help.setWindowTitle(_translate("Dialog_help", "Help"))
        self.label_2.setText(_translate("Dialog_help", "This is a control interface for KiKusui PBZ 20-20 Arbitrary Power Supply.\n"
"NI VISA shall be installed prior the usage of this control interface."))
        self.label_3.setText(_translate("Dialog_help", "<html><head/><body><p><a href=\"https://manual.kikusui.co.jp/P/PBZ_USERS_V3_E5.pdf\"><span style=\" text-decoration: underline; color:#0000ff;\">Press here for User Manual</span></a></p></body></html>"))
        self.label_4.setText(_translate("Dialog_help", "<html><head/><body><p><a href=\"https://manual.kikusui.co.jp/P/PBZ_IF_V2_E3.pdf\"><span style=\" text-decoration: underline; color:#0000ff;\">Press here to access the Interface Manual</span></a></p></body></html>"))
        self.label_email.setText(_translate("Dialog_help", "<html><head/><body><p><a href=\"https://outlook.live.com/mail/0/inbox\"><span style=\" text-decoration: underline; color:#0000ff;\">If there is any technical support or further understanding, please contact: chenhui_k029@hotmail.com"))
        self.label.setText(_translate("Dialog_help", "Created @2021/4 version 1.0"))

import UIpy.equipment_pic_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_help = QtWidgets.QDialog()
    ui = Ui_Dialog_help()
    ui.setupUi(Dialog_help)
    Dialog_help.show()
    sys.exit(app.exec_())
