# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '11_msg_box_ok.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msgboxok(object):
    def setupUi(self, msgboxok):
        msgboxok.setObjectName("msgboxok")
        msgboxok.resize(417, 186)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(msgboxok)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(msgboxok)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(msgboxok)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(msgboxok)
        self.buttonBox.accepted.connect(msgboxok.accept)
        self.buttonBox.rejected.connect(msgboxok.reject)
        QtCore.QMetaObject.connectSlotsByName(msgboxok)

    def retranslateUi(self, msgboxok):
        _translate = QtCore.QCoreApplication.translate
        msgboxok.setWindowTitle(_translate("msgboxok", "Warning"))
        self.label.setText(_translate("msgboxok", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    msgboxok = QtWidgets.QDialog()
    ui = Ui_msgboxok()
    ui.setupUi(msgboxok)
    msgboxok.show()
    sys.exit(app.exec_())
