# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '10_msg_box_ok_cancel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_msgboxokcancel(object):
    def setupUi(self, msgboxokcancel):
        msgboxokcancel.setObjectName("msgboxokcancel")
        msgboxokcancel.resize(419, 190)
        self.verticalLayout = QtWidgets.QVBoxLayout(msgboxokcancel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.msgboxokcancel_label = QtWidgets.QLabel(msgboxokcancel)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.msgboxokcancel_label.setFont(font)
        self.msgboxokcancel_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msgboxokcancel_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.msgboxokcancel_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msgboxokcancel_label.setObjectName("msgboxokcancel_label")
        self.verticalLayout_2.addWidget(self.msgboxokcancel_label)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.dialogButtonBox = QtWidgets.QDialogButtonBox(msgboxokcancel)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.dialogButtonBox.setFont(font)
        self.dialogButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.dialogButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialogButtonBox.setObjectName("dialogButtonBox")
        self.verticalLayout.addWidget(self.dialogButtonBox)

        self.retranslateUi(msgboxokcancel)
        self.dialogButtonBox.accepted.connect(msgboxokcancel.accept)
        self.dialogButtonBox.rejected.connect(msgboxokcancel.reject)
        QtCore.QMetaObject.connectSlotsByName(msgboxokcancel)

    def retranslateUi(self, msgboxokcancel):
        _translate = QtCore.QCoreApplication.translate
        msgboxokcancel.setWindowTitle(_translate("msgboxokcancel", "Info"))
        self.msgboxokcancel_label.setText(_translate("msgboxokcancel", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    msgboxokcancel = QtWidgets.QDialog()
    ui = Ui_msgboxokcancel()
    ui.setupUi(msgboxokcancel)
    msgboxokcancel.show()
    sys.exit(app.exec_())
