# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '12_new_entry_ok_cancel.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_new_entry_dialog(object):
    def setupUi(self, new_entry_dialog):
        new_entry_dialog.setObjectName("new_entry_dialog")
        new_entry_dialog.resize(380, 139)
        self.verticalLayout = QtWidgets.QVBoxLayout(new_entry_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.msgboxokcancel_label = QtWidgets.QLabel(new_entry_dialog)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        self.msgboxokcancel_label.setFont(font)
        self.msgboxokcancel_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.msgboxokcancel_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.msgboxokcancel_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.msgboxokcancel_label.setObjectName("msgboxokcancel_label")
        self.verticalLayout_2.addWidget(self.msgboxokcancel_label)
        self.lineEdit_new_entry = QtWidgets.QLineEdit(new_entry_dialog)
        self.lineEdit_new_entry.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_new_entry.setObjectName("lineEdit_new_entry")
        self.verticalLayout_2.addWidget(self.lineEdit_new_entry)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.dialogButtonBox = QtWidgets.QDialogButtonBox(new_entry_dialog)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.dialogButtonBox.setFont(font)
        self.dialogButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.dialogButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.dialogButtonBox.setObjectName("dialogButtonBox")
        self.verticalLayout.addWidget(self.dialogButtonBox)

        self.retranslateUi(new_entry_dialog)
        self.dialogButtonBox.accepted.connect(new_entry_dialog.accept)
        self.dialogButtonBox.rejected.connect(new_entry_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(new_entry_dialog)

    def retranslateUi(self, new_entry_dialog):
        _translate = QtCore.QCoreApplication.translate
        new_entry_dialog.setWindowTitle(_translate("new_entry_dialog", "Info"))
        self.msgboxokcancel_label.setText(_translate("new_entry_dialog", "New Entry:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    new_entry_dialog = QtWidgets.QDialog()
    ui = Ui_new_entry_dialog()
    ui.setupUi(new_entry_dialog)
    new_entry_dialog.show()
    sys.exit(app.exec_())
